### ISSUE TITLE
默认pattern中包含非ascii字符导致Grok异常

### ISSUE THREAD

**Issue by thuhak** [garyelephant/pygrok#37]
异常如下：

```
Traceback (most recent call last):
  File "/Users/thuhak.zhou/PycharmProjects/dnslog-parser/dnslog-parser.py", line 68, in <module>
    query_pat = Grok('%{WORD}')
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygrok/pygrok.py", line 15, in __init__
    self.predefined_patterns = _reload_patterns(DEFAULT_PATTERNS_DIRS)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygrok/pygrok.py", line 83, in _reload_patterns
    patterns = _load_patterns_from_file(os.path.join(dir, f))
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygrok/pygrok.py", line 94, in _load_patterns_from_file
    for l in f:
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3122: ordinal not in range(128)
```

导致问题出现的地点：

grok-patterns中的

MONTH \b(?:Jan(?:uary|uar)?|Feb(?:ruary|ruar)?|M(?:a|**ä**)?r(?:ch|z)?|Apr(?:il)?|Ma(?:y|i)?|Jun(?:e|i)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|O(?:c|k)?t(?:ober)?|Nov(?:ember)?|De(?:c|z)(?:ember)?)\b

**Comment by thuhak** [comment]
看起来是pypi上的版本比较旧导致的
